const BrandDeli = require('./projects/brandeli.js');
const boz = require('./projects/boz.js');
const routeplanner = require('./projects/routeplanner.js');

let projects = [];
projects.push(boz);
projects.push(routeplanner);
projects.push(BrandDeli);
projects.push(routeplanner);
projects.push(BrandDeli);
projects.push(boz);
projects.push(BrandDeli);
projects.push(boz);
projects.push(routeplanner);
projects.push(BrandDeli);
projects.push(boz);
projects.push(routeplanner);
projects.push(BrandDeli);
projects.push(boz);
module.exports = projects;
